model:
  embedder_name: "deepvk/USER-bge-m3"
  ffn_dim: 2048
  ffn_classes_dropout: 0.3
  ffn_text_dropout: 0.3
  device: "cuda"
  unfreeze_embedder: True
  optimizer_args:
     class_path: torch.optim.AdamW
     init_params:
        lr: 0.000005

data_module:
  tokenizer_name: "deepvk/USER-bge-m3"
  config: "task_creation_negatives"

trainer:
  accelerator: "gpu"
  val_check_interval: 5810

other:
  checkpoints_dir: "/data/checkpoints/sweeps"