model:
  embedder_name: "deepvk/USER-base"
  ffn_dim: 2048
  ffn_dropout: 0.1
  device: "cuda"
  unfreeze_embedder: False

data_module:
  batch_size: 16
  val_batch_size: 16
  num_workers: 20
  tokenizer_name: "deepvk/USER-base"
  config: "multiclass"

trainer:
  max_steps: 200
  accelerator: "gpu"
  val_check_interval: 100
  gradient_clip_val: 0.0
  log_every_n_steps: 50

other:
  wandb_project: "universal_classifier"
  checkpoints_dir: "/data/checkpoints"